name: Build and Push Container

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Login to GHCR
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u paulgarias --password-stdin

      - name: Build image
        run: docker build -t ghcr.io/paulgarias/python-env-crispie:latest .

      - name: Push image
        run: docker push ghcr.io/paulgarias/python-env-crispie:latest